/**
 * server.ts — Runtime bootstrap
 *
 * Responsible for:
 *   - Loading env vars (dotenv)
 *   - Asserting required secrets before the process binds a port
 *   - Creating the Express app via createApp() (see src/server/app.ts)
 *   - Attaching the /api/server-info route (needs access to the resolved
 *     protocol and PORT, which aren't known until the server object is built)
 *   - Creating the http/https Node server and attaching Vite's dev middleware
 *   - Starting the listener
 *
 * All API routes and middleware live in src/server/app.ts so that tests can
 * import createApp() without spinning up a port or a Vite dev server.
 */
import 'dotenv/config';
import { createServer as createViteServer } from 'vite';
import http from 'node:http';
import https from 'node:https';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import express from 'express';

// Side-effect import — runs all migrations and seeds the database before any
// route handler is registered. Must come before createApp() so the database
// schema is ready when routes try to query it.
import './src/server/db.js';
import { createApp } from './src/server/app.js';
import { getLocalIP, getTunnelUrl } from './src/server/helpers.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
export const PORT = 3000;

// ── Guard — fail fast if secrets are missing ────────────────────────────────
const JWT_SECRET = process.env.JWT_SECRET;
if (!JWT_SECRET) {
  console.error(
    'FATAL: JWT_SECRET environment variable is not set. ' +
      "Generate one with: node -e \"console.log(require('crypto').randomBytes(32).toString('hex'))\""
  );
  process.exit(1);
}

// ── Process-level error guards ────────────────────────────────────────────────
// Unhandled rejections crash Node 18+ silently — log before exit so the failure
// is observable in logs rather than disappearing without a trace.
process.on('unhandledRejection', reason => {
  console.error('[unhandledRejection]', reason);
});
process.on('uncaughtException', err => {
  console.error('[uncaughtException]', err);
  process.exit(1);
});

// ── Build the Express application ────────────────────────────────────────────
const app = createApp();

// ── /api/server-info ─────────────────────────────────────────────────────────
// Lives here (not in app.ts) because it reads `app.protocol` and `PORT`, which
// are set after the Node server is created below. Reading them at request time
// via (app as any).protocol means the handler always sees the final values.
app.get('/api/server-info', (_req, res) => {
  const ip = getLocalIP();
  const protocol = (app as any).protocol || 'http';
  const lanUrl = `${protocol}://${ip}:${PORT}`;
  const tunnelUrl = getTunnelUrl();
  res.json({
    ip,
    port: PORT,
    protocol,
    mobileUrl: tunnelUrl ?? lanUrl,
    tunnelUrl: tunnelUrl ?? null,
  });
});

// ── HTTPS certificate helper ──────────────────────────────────────────────────
// Reads the dev-key.pem / dev-cert.pem pair generated by generate-certs.js.
// Returns null in any environment where the files are absent (CI, production
// behind nginx, etc.) so the server gracefully falls back to HTTP.
function getHttpsOptions() {
  const devKeyPath = path.join(__dirname, 'dev-key.pem');
  const devCertPath = path.join(__dirname, 'dev-cert.pem');
  if (fs.existsSync(devKeyPath) && fs.existsSync(devCertPath)) {
    console.log('✓ Using SSL certificates (dev-key.pem / dev-cert.pem)');
    return { key: fs.readFileSync(devKeyPath), cert: fs.readFileSync(devCertPath) };
  }
  return null;
}

// ── Create the HTTP(S) server ─────────────────────────────────────────────────
// The Node http.Server is created up-front (before Vite attaches) so that
// Vite's WebSocket upgrade handler can share the same server instance.
// WebSocket upgrade events fire on the Node server directly — they never reach
// Express middleware — so Vite must be attached to the same server to receive
// upgrades forwarded by the Cloudflare tunnel.
let protocol = 'http';
const httpsOptions = getHttpsOptions();
let nodeServer: http.Server | https.Server;

if (httpsOptions) {
  try {
    nodeServer = https.createServer(httpsOptions, app);
    protocol = 'https';
  } catch (err: any) {
    console.log(`ℹ HTTPS setup failed, using HTTP: ${err.message}`);
    nodeServer = http.createServer(app);
  }
} else {
  nodeServer = http.createServer(app);
}

// Make protocol available to /api/server-info at request time
(app as any).protocol = protocol;

// ── Vite dev middleware or static production build ───────────────────────────
if (process.env.NODE_ENV !== 'production') {
  const vite = await createViteServer({
    server: {
      middlewareMode: true,
      // Attach Vite's HMR WebSocket handler to the same Node server so upgrade
      // events from the Cloudflare tunnel reach Vite correctly.
      hmr: process.env.DISABLE_HMR === 'true' ? false : { server: nodeServer },
    },
    appType: 'spa',
  });
  app.use(vite.middlewares);
} else {
  app.use(express.static('dist'));
  app.get('*', (_req, res) => {
    res.sendFile(path.join(__dirname, 'dist', 'index.html'));
  });
}

// ── Graceful shutdown ─────────────────────────────────────────────────────────
// Drain in-flight requests before exiting so SQLite WAL is not left dirty and
// clients receive a complete response rather than a connection reset.
const shutdown = () => {
  nodeServer.close(() => {
    console.log('Server closed gracefully');
    process.exit(0);
  });
};
process.on('SIGTERM', shutdown);
process.on('SIGINT', shutdown);

// ── Start listening ───────────────────────────────────────────────────────────
nodeServer.listen(PORT, '0.0.0.0', () => {
  if (protocol === 'https') {
    console.log(`🔒 HTTPS Server running on https://localhost:${PORT}`);
    console.log(`🔒 HTTPS Server running on https://127.0.0.1:${PORT}`);
    console.log(`✓ Camera scanning enabled via HTTPS`);
  } else {
    console.log(`🔓 HTTP Server running on http://localhost:${PORT}`);
    console.log(`ℹ No SSL cert files found. HTTPS is required for camera scanning.`);
  }
});
